### ISSUE TITLE
编译过程

### ISSUE THREAD

**Issue by Rae-Denis** [DiscreteTom/Compiler-Grammatical-Analyzer-LR#1]
请问由于不太了解Qt creator，把您的代码导进去后遇到了一系列问题，想请教一下您可以吗？
1、在创建项目的时候是选的qt console application的选项吗,那个build system是选的qmake吗，还有之后的一些选项有没有什么要求？
2、我按照一路点确定按照默认创建好项目后运行main.cpp出现了一些错误，出错的地方有（好像评论不能贴图片我就复制过来一点）  getline(cin, t);#include <bits/stl_algo.h>、#include <algorithm>、#include <QtCore/qglobal.h>还有其他共46个问题，有很大一部分显示是出现在一个名为qcoreapplication.h的地方，请问您知不知道是哪里出了问题？
3、您code里那个后缀为.gitignore的文件该怎么使用，可以指点一下吗？
4、在运行后编译输出框输出了以下语句：Error while building/deploying project LR4 (kit: Desktop Qt 5.9.0 MinGW 32bit)
When executing step "Make"，在网上搜了很久没能解决，希望您能指教。
您的项目给了我莫大的帮助，不好意思因为这些问题和自身能力不足打扰到您，希望如果您方便的话可以指点一二，十分感谢

**Comment by DiscreteTom** [comment]
不好意思，没watch这个repo，所以现在才看到您的issue。。
相信过了这么长时间您应该已经解决了这些问题。。而且我目前也不用QT搞开发了，我也不知道怎么解决哈哈
不好意思
